# Generated by Django 5.2 on 2025-04-09 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('overall_score', models.CharField(blank=True, max_length=50, null=True)),
                ('web_links', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'institutions',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'userinfo',
                'verbose_name_plural': 'userinfos',
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='FacultyStudent',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_student', to='api.institution')),
            ],
            options={
                'db_table': 'faculty_student',
            },
        ),
        migrations.CreateModel(
            name='EmploymentOutcomes',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment_outcomes', to='api.institution')),
            ],
            options={
                'db_table': 'employment_outcomes',
            },
        ),
        migrations.CreateModel(
            name='EmployerReputation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_reputation', to='api.institution')),
            ],
            options={
                'db_table': 'employer_reputation',
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('size', models.CharField(blank=True, choices=[('Extra Large', 'Extra Large'), ('Large', 'Large'), ('Medium', 'Medium'), ('Small', 'Small')], max_length=20, null=True)),
                ('focus', models.CharField(blank=True, choices=[('Full comprehensive', 'Full comprehensive'), ('Comprehensive', 'Comprehensive'), ('Focused', 'Focused'), ('Specialist', 'Specialist')], max_length=20, null=True)),
                ('research', models.CharField(blank=True, choices=[('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20, null=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='api.institution')),
            ],
            options={
                'db_table': 'classification',
            },
        ),
        migrations.CreateModel(
            name='CitationsPerFaculty',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citations_per_faculty', to='api.institution')),
            ],
            options={
                'db_table': 'citations_per_faculty',
            },
        ),
        migrations.CreateModel(
            name='AcademicReputation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_reputation', to='api.institution')),
            ],
            options={
                'db_table': 'academic_reputation',
            },
        ),
        migrations.CreateModel(
            name='InternationalFaculty',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='international_faculty', to='api.institution')),
            ],
            options={
                'db_table': 'international_faculty',
            },
        ),
        migrations.CreateModel(
            name='InternationalResearchNetwork',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='international_research_network', to='api.institution')),
            ],
            options={
                'db_table': 'international_research_network',
            },
        ),
        migrations.CreateModel(
            name='InternationalStudents',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='international_students', to='api.institution')),
            ],
            options={
                'db_table': 'international_students',
            },
        ),
        migrations.CreateModel(
            name='Sustainability',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sustainability', to='api.institution')),
            ],
            options={
                'db_table': 'sustainability',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('notification_email', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
    ]
