# Generated by Django 5.2 on 2025-04-06 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('overall_score', models.CharField(blank=True, max_length=50, null=True)),
                ('web_links', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'institutions',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='FacultyStudent',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_student', to='api.institution')),
            ],
            options={
                'db_table': 'faculty_student',
            },
        ),
        migrations.CreateModel(
            name='EmploymentOutcomes',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment_outcomes', to='api.institution')),
            ],
            options={
                'db_table': 'employment_outcomes',
            },
        ),
        migrations.CreateModel(
            name='EmployerReputation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_reputation', to='api.institution')),
            ],
            options={
                'db_table': 'employer_reputation',
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('size', models.CharField(blank=True, choices=[('Extra Large', 'Extra Large'), ('Large', 'Large'), ('Medium', 'Medium'), ('Small', 'Small')], max_length=20, null=True)),
                ('focus', models.CharField(blank=True, choices=[('Full comprehensive', 'Full comprehensive'), ('Comprehensive', 'Comprehensive'), ('Focused', 'Focused'), ('Specialist', 'Specialist')], max_length=20, null=True)),
                ('research', models.CharField(blank=True, choices=[('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20, null=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='api.institution')),
            ],
            options={
                'db_table': 'classification',
            },
        ),
        migrations.CreateModel(
            name='CitationsPerFaculty',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citations_per_faculty', to='api.institution')),
            ],
            options={
                'db_table': 'citations_per_faculty',
            },
        ),
        migrations.CreateModel(
            name='AcademicReputation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_reputation', to='api.institution')),
            ],
            options={
                'db_table': 'academic_reputation',
            },
        ),
        migrations.CreateModel(
            name='InternationalFaculty',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='international_faculty', to='api.institution')),
            ],
            options={
                'db_table': 'international_faculty',
            },
        ),
        migrations.CreateModel(
            name='InternationalResearchNetwork',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='international_research_network', to='api.institution')),
            ],
            options={
                'db_table': 'international_research_network',
            },
        ),
        migrations.CreateModel(
            name='InternationalStudents',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='international_students', to='api.institution')),
            ],
            options={
                'db_table': 'international_students',
            },
        ),
        migrations.CreateModel(
            name='Sustainability',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sustainability', to='api.institution')),
            ],
            options={
                'db_table': 'sustainability',
            },
        ),
    ]
