# Generated by Django 5.1.7 on 2025-04-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_academicreputation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citationsperfaculty',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='classification',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='employerreputation',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='employmentoutcomes',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='facultystudent',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='sustainability',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='internationalfaculty',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='internationalresearchnetwork',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='internationalstudents',
            name='institution',
        ),
        migrations.DeleteModel(
            name='AcademicReputation',
        ),
        migrations.DeleteModel(
            name='CitationsPerFaculty',
        ),
        migrations.DeleteModel(
            name='Classification',
        ),
        migrations.DeleteModel(
            name='EmployerReputation',
        ),
        migrations.DeleteModel(
            name='EmploymentOutcomes',
        ),
        migrations.DeleteModel(
            name='FacultyStudent',
        ),
        migrations.DeleteModel(
            name='Sustainability',
        ),
        migrations.DeleteModel(
            name='InternationalFaculty',
        ),
        migrations.DeleteModel(
            name='InternationalResearchNetwork',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='InternationalStudents',
        ),
    ]
