# Generated by Django 5.1.7 on 2025-04-07 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_remove_citationsperfaculty_institution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('overall_score', models.FloatField()),
                ('web_links', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='FacultyStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('rank', models.CharField(max_length=10)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_student', to='schools.institution')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentOutcomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('rank', models.CharField(max_length=10)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_outcomes', to='schools.institution')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('rank', models.CharField(max_length=10)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_reputation', to='schools.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('Extra Large', 'Extra Large'), ('Large', 'Large'), ('Medium', 'Medium'), ('Small', 'Small')], max_length=20)),
                ('focus', models.CharField(choices=[('Full Comprehensive', 'Full Comprehensive'), ('Comprehensive', 'Comprehensive'), ('Focused', 'Focused'), ('Specialist', 'Specialist')], max_length=30)),
                ('research', models.CharField(choices=[('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='schools.institution')),
            ],
        ),
        migrations.CreateModel(
            name='CitationsPerFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('rank', models.CharField(max_length=10)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations_per_faculty', to='schools.institution')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('rank', models.CharField(max_length=10)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_reputation', to='schools.institution')),
            ],
        ),
        migrations.CreateModel(
            name='InternationalFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('rank', models.CharField(max_length=10)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='international_faculty', to='schools.institution')),
            ],
        ),
        migrations.CreateModel(
            name='InternationalResearchNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('rank', models.CharField(max_length=10)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='international_research_network', to='schools.institution')),
            ],
        ),
        migrations.CreateModel(
            name='InternationalStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('rank', models.CharField(max_length=10)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='international_students', to='schools.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Sustainability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('rank', models.CharField(max_length=10)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sustainability', to='schools.institution')),
            ],
        ),
    ]
