# Generated by Django 5.1.7 on 2025-04-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_institution_facultystudent_employmentoutcomes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicreputation',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='citationsperfaculty',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employerreputation',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employmentoutcomes',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='facultystudent',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='institution',
            name='overall_score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='internationalfaculty',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='internationalresearchnetwork',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='internationalstudents',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sustainability',
            name='score',
            field=models.CharField(max_length=10),
        ),
    ]
