### 1. Initiate Google Login
# GET http://localhost:8000/api/auth/sigin_google/
# Accept: application/json


### Upload a PDF to Supabase
POST http://localhost:8000/api/user/profile/upload_document/
Content-Type: multipart/form-data; boundary=test123

--test123
Content-Disposition: form-data; name="file"; filename="contract.pdf"

< ./contract.pdf
--test123
Content-Disposition: form-data; name="document_type"

legal
--test123--

