services:
  - type: web
    name: schooltracker-backend
    env: python
    region: oregon
    buildCommand: bash ./build.sh
    startCommand: gunicorn schooltracker_backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: schooltracker-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
      - key: PYTHONUNBUFFERED
        value: 1
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_BUCKET
        value: profile-pictures
    staticPublishPath: ./staticfiles

databases:
  - name: schooltracker-db
    databaseName: schooltracker
    user: schooltracker
    region: oregon
