# Generated by Django 5.1.7 on 2025-03-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
