# Generated by Django 5.1.7 on 2025-04-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='application',
            name='accepted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='rejected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='degree_type',
            field=models.CharField(choices=[('BSc', 'Bachelor of Science'), ('BA', 'Bachelor of Arts'), ('BEng', 'Bachelor of Engineering'), ('LLB', 'Bachelor of Laws'), ('MBBS', 'Bachelor of Medicine & Surgery'), ('BEd', 'Bachelor of Education'), ('MSc', 'Master of Science'), ('MA', 'Master of Arts'), ('MEng', 'Master of Engineering'), ('LLM', 'Master of Laws'), ('MBA', 'Master of Business Administration'), ('PhD', 'Doctor of Philosophy'), ('PGD', 'Postgraduate Diploma'), ('HND', 'Higher National Diploma'), ('OND', 'Ordinary National Diploma'), ('Other', 'Other')], max_length=50),
        ),
    ]
