# Generated by Django 5.1.7 on 2025-04-05 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_options_application_accepted_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='university',
            new_name='school',
        ),
    ]
