# Generated by Django 5.1.7 on 2025-04-07 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_rename_university_program_school'),
        ('schools', '0006_alter_academicreputation_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='school',
        ),
        migrations.AddField(
            model_name='program',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.institution'),
            preserve_default=False,
        ),
    ]
