export interface Timezone {
	value: string;
	label: string;
	offset: string;
}

export const timezones: Timezone[] = [
	{ value: "Pacific/Midway", label: "Midway", offset: "UTC-11:00" },
	{ value: "Pacific/Niue", label: "Niue", offset: "UTC-11:00" },
	{ value: "Pacific/Pago_Pago", label: "Pago Pago", offset: "UTC-11:00" },
	{ value: "America/Adak", label: "Adak", offset: "UTC-10:00" },
	{ value: "Pacific/Honolulu", label: "Honolulu", offset: "UTC-10:00" },
	{ value: "Pacific/Johnston", label: "Johnston", offset: "UTC-10:00" },
	{ value: "Pacific/Rarotonga", label: "Rarotonga", offset: "UTC-10:00" },
	{ value: "Pacific/Tahiti", label: "Tahiti", offset: "UTC-10:00" },
	{ value: "Pacific/Marquesas", label: "Marquesas", offset: "UTC-09:30" },
	{ value: "America/Anchorage", label: "Anchorage", offset: "UTC-09:00" },
	{ value: "Pacific/Gambier", label: "Gambier", offset: "UTC-09:00" },
	{ value: "America/Juneau", label: "Juneau", offset: "UTC-09:00" },
	{ value: "America/Nome", label: "Nome", offset: "UTC-09:00" },
	{ value: "America/Sitka", label: "Sitka", offset: "UTC-09:00" },
	{ value: "America/Yakutat", label: "Yakutat", offset: "UTC-09:00" },
	{ value: "America/Dawson", label: "Dawson", offset: "UTC-08:00" },
	{ value: "America/Los_Angeles", label: "Los Angeles", offset: "UTC-08:00" },
	{ value: "America/Metlakatla", label: "Metlakatla", offset: "UTC-08:00" },
	{ value: "Pacific/Pitcairn", label: "Pitcairn", offset: "UTC-08:00" },
	{ value: "America/Santa_Isabel", label: "Santa Isabel", offset: "UTC-08:00" },
	{ value: "America/Tijuana", label: "Tijuana", offset: "UTC-08:00" },
	{ value: "America/Vancouver", label: "Vancouver", offset: "UTC-08:00" },
	{ value: "America/Whitehorse", label: "Whitehorse", offset: "UTC-08:00" },
	{ value: "America/Boise", label: "Boise", offset: "UTC-07:00" },
	{
		value: "America/Cambridge_Bay",
		label: "Cambridge Bay",
		offset: "UTC-07:00",
	},
	{ value: "America/Chihuahua", label: "Chihuahua", offset: "UTC-07:00" },
	{ value: "America/Creston", label: "Creston", offset: "UTC-07:00" },
	{ value: "America/Dawson_Creek", label: "Dawson Creek", offset: "UTC-07:00" },
	{ value: "America/Denver", label: "Denver", offset: "UTC-07:00" },
	{ value: "America/Edmonton", label: "Edmonton", offset: "UTC-07:00" },
	{ value: "America/Hermosillo", label: "Hermosillo", offset: "UTC-07:00" },
	{ value: "America/Inuvik", label: "Inuvik", offset: "UTC-07:00" },
	{ value: "America/Mazatlan", label: "Mazatlan", offset: "UTC-07:00" },
	{ value: "America/Ojinaga", label: "Ojinaga", offset: "UTC-07:00" },
	{ value: "America/Phoenix", label: "Phoenix", offset: "UTC-07:00" },
	{ value: "America/Shiprock", label: "Shiprock", offset: "UTC-07:00" },
	{ value: "America/Yellowknife", label: "Yellowknife", offset: "UTC-07:00" },
	{
		value: "America/Bahia_Banderas",
		label: "Bahia Banderas",
		offset: "UTC-06:00",
	},
	{ value: "America/Belize", label: "Belize", offset: "UTC-06:00" },
	{
		value: "America/North_Dakota/Beulah",
		label: "Beulah",
		offset: "UTC-06:00",
	},
	{ value: "America/Cancun", label: "Cancun", offset: "UTC-06:00" },
	{
		value: "America/North_Dakota/Center",
		label: "Center",
		offset: "UTC-06:00",
	},
	{ value: "America/Chicago", label: "Chicago", offset: "UTC-06:00" },
	{ value: "America/Costa_Rica", label: "Costa Rica", offset: "UTC-06:00" },
	{ value: "Pacific/Easter", label: "Easter", offset: "UTC-06:00" },
	{ value: "America/El_Salvador", label: "El Salvador", offset: "UTC-06:00" },
	{ value: "Pacific/Galapagos", label: "Galapagos", offset: "UTC-06:00" },
	{ value: "America/Guatemala", label: "Guatemala", offset: "UTC-06:00" },
	{ value: "America/Indiana/Knox", label: "Knox", offset: "UTC-06:00" },
	{ value: "America/Managua", label: "Managua", offset: "UTC-06:00" },
	{ value: "America/Matamoros", label: "Matamoros", offset: "UTC-06:00" },
	{ value: "America/Menominee", label: "Menominee", offset: "UTC-06:00" },
	{ value: "America/Merida", label: "Merida", offset: "UTC-06:00" },
	{ value: "America/Mexico_City", label: "Mexico City", offset: "UTC-06:00" },
	{ value: "America/Monterrey", label: "Monterrey", offset: "UTC-06:00" },
	{
		value: "America/North_Dakota/New_Salem",
		label: "New Salem",
		offset: "UTC-06:00",
	},
	{ value: "America/Rainy_River", label: "Rainy River", offset: "UTC-06:00" },
	{ value: "America/Rankin_Inlet", label: "Rankin Inlet", offset: "UTC-06:00" },
	{ value: "America/Regina", label: "Regina", offset: "UTC-06:00" },
	{ value: "America/Resolute", label: "Resolute", offset: "UTC-06:00" },
	{
		value: "America/Swift_Current",
		label: "Swift Current",
		offset: "UTC-06:00",
	},
	{ value: "America/Tegucigalpa", label: "Tegucigalpa", offset: "UTC-06:00" },
	{
		value: "America/Indiana/Tell_City",
		label: "Tell City",
		offset: "UTC-06:00",
	},
	{ value: "America/Winnipeg", label: "Winnipeg", offset: "UTC-06:00" },
	{ value: "America/Atikokan", label: "Atikokan", offset: "UTC-05:00" },
	{ value: "America/Bogota", label: "Bogota", offset: "UTC-05:00" },
	{ value: "America/Cayman", label: "Cayman", offset: "UTC-05:00" },
	{ value: "America/Detroit", label: "Detroit", offset: "UTC-05:00" },
	{ value: "America/Grand_Turk", label: "Grand Turk", offset: "UTC-05:00" },
	{ value: "America/Guayaquil", label: "Guayaquil", offset: "UTC-05:00" },
	{ value: "America/Havana", label: "Havana", offset: "UTC-05:00" },
	{
		value: "America/Indiana/Indianapolis",
		label: "Indianapolis",
		offset: "UTC-05:00",
	},
	{ value: "America/Iqaluit", label: "Iqaluit", offset: "UTC-05:00" },
	{ value: "America/Jamaica", label: "Jamaica", offset: "UTC-05:00" },
	{ value: "America/Lima", label: "Lima", offset: "UTC-05:00" },
	{
		value: "America/Kentucky/Louisville",
		label: "Louisville",
		offset: "UTC-05:00",
	},
	{ value: "America/Indiana/Marengo", label: "Marengo", offset: "UTC-05:00" },
	{
		value: "America/Kentucky/Monticello",
		label: "Monticello",
		offset: "UTC-05:00",
	},
	{ value: "America/Montreal", label: "Montreal", offset: "UTC-05:00" },
	{ value: "America/Nassau", label: "Nassau", offset: "UTC-05:00" },
	{ value: "America/New_York", label: "New York", offset: "UTC-05:00" },
	{ value: "America/Nipigon", label: "Nipigon", offset: "UTC-05:00" },
	{ value: "America/Panama", label: "Panama", offset: "UTC-05:00" },
	{ value: "America/Pangnirtung", label: "Pangnirtung", offset: "UTC-05:00" },
	{
		value: "America/Indiana/Petersburg",
		label: "Petersburg",
		offset: "UTC-05:00",
	},
	{
		value: "America/Port-au-Prince",
		label: "Port-au-Prince",
		offset: "UTC-05:00",
	},
	{ value: "America/Thunder_Bay", label: "Thunder Bay", offset: "UTC-05:00" },
	{ value: "America/Toronto", label: "Toronto", offset: "UTC-05:00" },
	{ value: "America/Indiana/Vevay", label: "Vevay", offset: "UTC-05:00" },
	{
		value: "America/Indiana/Vincennes",
		label: "Vincennes",
		offset: "UTC-05:00",
	},
	{ value: "America/Indiana/Winamac", label: "Winamac", offset: "UTC-05:00" },
	{ value: "America/Caracas", label: "Caracas", offset: "UTC-04:30" },
	{ value: "America/Anguilla", label: "Anguilla", offset: "UTC-04:00" },
	{ value: "America/Antigua", label: "Antigua", offset: "UTC-04:00" },
	{ value: "America/Aruba", label: "Aruba", offset: "UTC-04:00" },
	{ value: "America/Asuncion", label: "Asuncion", offset: "UTC-04:00" },
	{ value: "America/Barbados", label: "Barbados", offset: "UTC-04:00" },
	{ value: "Atlantic/Bermuda", label: "Bermuda", offset: "UTC-04:00" },
	{ value: "America/Blanc-Sablon", label: "Blanc-Sablon", offset: "UTC-04:00" },
	{ value: "America/Boa_Vista", label: "Boa Vista", offset: "UTC-04:00" },
	{ value: "America/Campo_Grande", label: "Campo Grande", offset: "UTC-04:00" },
	{ value: "America/Cuiaba", label: "Cuiaba", offset: "UTC-04:00" },
	{ value: "America/Curacao", label: "Curacao", offset: "UTC-04:00" },
	{ value: "America/Dominica", label: "Dominica", offset: "UTC-04:00" },
	{ value: "America/Eirunepe", label: "Eirunepe", offset: "UTC-04:00" },
	{ value: "America/Glace_Bay", label: "Glace Bay", offset: "UTC-04:00" },
	{ value: "America/Goose_Bay", label: "Goose Bay", offset: "UTC-04:00" },
	{ value: "America/Grenada", label: "Grenada", offset: "UTC-04:00" },
	{ value: "America/Guadeloupe", label: "Guadeloupe", offset: "UTC-04:00" },
	{ value: "America/Guyana", label: "Guyana", offset: "UTC-04:00" },
	{ value: "America/Halifax", label: "Halifax", offset: "UTC-04:00" },
	{ value: "America/Kralendijk", label: "Kralendijk", offset: "UTC-04:00" },
	{ value: "America/La_Paz", label: "La Paz", offset: "UTC-04:00" },
	{
		value: "America/Lower_Princes",
		label: "Lower Princes",
		offset: "UTC-04:00",
	},
	{ value: "America/Manaus", label: "Manaus", offset: "UTC-04:00" },
	{ value: "America/Marigot", label: "Marigot", offset: "UTC-04:00" },
	{ value: "America/Martinique", label: "Martinique", offset: "UTC-04:00" },
	{ value: "America/Moncton", label: "Moncton", offset: "UTC-04:00" },
	{ value: "America/Montserrat", label: "Montserrat", offset: "UTC-04:00" },
	{ value: "Antarctica/Palmer", label: "Palmer", offset: "UTC-04:00" },
	{
		value: "America/Port_of_Spain",
		label: "Port of Spain",
		offset: "UTC-04:00",
	},
	{ value: "America/Porto_Velho", label: "Porto Velho", offset: "UTC-04:00" },
	{ value: "America/Puerto_Rico", label: "Puerto Rico", offset: "UTC-04:00" },
	{ value: "America/Rio_Branco", label: "Rio Branco", offset: "UTC-04:00" },
	{ value: "America/Santiago", label: "Santiago", offset: "UTC-04:00" },
	{
		value: "America/Santo_Domingo",
		label: "Santo Domingo",
		offset: "UTC-04:00",
	},
	{
		value: "America/St_Barthelemy",
		label: "St. Barthelemy",
		offset: "UTC-04:00",
	},
	{ value: "America/St_Kitts", label: "St. Kitts", offset: "UTC-04:00" },
	{ value: "America/St_Lucia", label: "St. Lucia", offset: "UTC-04:00" },
	{ value: "America/St_Thomas", label: "St. Thomas", offset: "UTC-04:00" },
	{ value: "America/St_Vincent", label: "St. Vincent", offset: "UTC-04:00" },
	{ value: "America/Thule", label: "Thule", offset: "UTC-04:00" },
	{ value: "America/Tortola", label: "Tortola", offset: "UTC-04:00" },
	{ value: "America/St_Johns", label: "St. Johns", offset: "UTC-03:30" },
	{ value: "America/Araguaina", label: "Araguaina", offset: "UTC-03:00" },
	{ value: "America/Bahia", label: "Bahia", offset: "UTC-03:00" },
	{ value: "America/Belem", label: "Belem", offset: "UTC-03:00" },
	{
		value: "America/Argentina/Buenos_Aires",
		label: "Buenos Aires",
		offset: "UTC-03:00",
	},
	{
		value: "America/Argentina/Catamarca",
		label: "Catamarca",
		offset: "UTC-03:00",
	},
	{ value: "America/Cayenne", label: "Cayenne", offset: "UTC-03:00" },
	{ value: "America/Argentina/Cordoba", label: "Cordoba", offset: "UTC-03:00" },
	{ value: "America/Fortaleza", label: "Fortaleza", offset: "UTC-03:00" },
	{ value: "America/Godthab", label: "Godthab", offset: "UTC-03:00" },
	{ value: "America/Argentina/Jujuy", label: "Jujuy", offset: "UTC-03:00" },
	{
		value: "America/Argentina/La_Rioja",
		label: "La Rioja",
		offset: "UTC-03:00",
	},
	{ value: "America/Maceio", label: "Maceio", offset: "UTC-03:00" },
	{ value: "America/Argentina/Mendoza", label: "Mendoza", offset: "UTC-03:00" },
	{ value: "America/Miquelon", label: "Miquelon", offset: "UTC-03:00" },
	{ value: "America/Montevideo", label: "Montevideo", offset: "UTC-03:00" },
	{ value: "America/Paramaribo", label: "Paramaribo", offset: "UTC-03:00" },
	{ value: "America/Recife", label: "Recife", offset: "UTC-03:00" },
	{
		value: "America/Argentina/Rio_Gallegos",
		label: "Rio Gallegos",
		offset: "UTC-03:00",
	},
	{ value: "Antarctica/Rothera", label: "Rothera", offset: "UTC-03:00" },
	{ value: "America/Argentina/Salta", label: "Salta", offset: "UTC-03:00" },
	{
		value: "America/Argentina/San_Juan",
		label: "San Juan",
		offset: "UTC-03:00",
	},
	{
		value: "America/Argentina/San_Luis",
		label: "San Luis",
		offset: "UTC-03:00",
	},
	{ value: "America/Santarem", label: "Santarem", offset: "UTC-03:00" },
	{ value: "America/Sao_Paulo", label: "Sao Paulo", offset: "UTC-03:00" },
	{ value: "Atlantic/Stanley", label: "Stanley", offset: "UTC-03:00" },
	{ value: "America/Argentina/Tucuman", label: "Tucuman", offset: "UTC-03:00" },
	{ value: "America/Argentina/Ushuaia", label: "Ushuaia", offset: "UTC-03:00" },
	{ value: "America/Noronha", label: "Noronha", offset: "UTC-02:00" },
	{
		value: "Atlantic/South_Georgia",
		label: "South Georgia",
		offset: "UTC-02:00",
	},
	{ value: "Atlantic/Azores", label: "Azores", offset: "UTC-01:00" },
	{ value: "Atlantic/Cape_Verde", label: "Cape Verde", offset: "UTC-01:00" },
	{ value: "America/Scoresbysund", label: "Scoresbysund", offset: "UTC-01:00" },
	{ value: "Africa/Abidjan", label: "Abidjan", offset: "UTC+00:00" },
	{ value: "Africa/Accra", label: "Accra", offset: "UTC+00:00" },
	{ value: "Africa/Bamako", label: "Bamako", offset: "UTC+00:00" },
	{ value: "Africa/Banjul", label: "Banjul", offset: "UTC+00:00" },
	{ value: "Africa/Bissau", label: "Bissau", offset: "UTC+00:00" },
	{ value: "Atlantic/Canary", label: "Canary", offset: "UTC+00:00" },
	{ value: "Africa/Casablanca", label: "Casablanca", offset: "UTC+00:00" },
	{ value: "Africa/Conakry", label: "Conakry", offset: "UTC+00:00" },
	{ value: "Africa/Dakar", label: "Dakar", offset: "UTC+00:00" },
	{ value: "America/Danmarkshavn", label: "Danmarkshavn", offset: "UTC+00:00" },
	{ value: "Europe/Dublin", label: "Dublin", offset: "UTC+00:00" },
	{ value: "Africa/El_Aaiun", label: "El Aaiun", offset: "UTC+00:00" },
	{ value: "Atlantic/Faroe", label: "Faroe", offset: "UTC+00:00" },
	{ value: "Africa/Freetown", label: "Freetown", offset: "UTC+00:00" },
	{ value: "Europe/Guernsey", label: "Guernsey", offset: "UTC+00:00" },
	{ value: "Europe/Isle_of_Man", label: "Isle of Man", offset: "UTC+00:00" },
	{ value: "Europe/Jersey", label: "Jersey", offset: "UTC+00:00" },
	{ value: "Europe/Lisbon", label: "Lisbon", offset: "UTC+00:00" },
	{ value: "Africa/Lome", label: "Lome", offset: "UTC+00:00" },
	{ value: "Europe/London", label: "London", offset: "UTC+00:00" },
	{ value: "Atlantic/Madeira", label: "Madeira", offset: "UTC+00:00" },
	{ value: "Africa/Monrovia", label: "Monrovia", offset: "UTC+00:00" },
	{ value: "Africa/Nouakchott", label: "Nouakchott", offset: "UTC+00:00" },
	{ value: "Africa/Ouagadougou", label: "Ouagadougou", offset: "UTC+00:00" },
	{ value: "Atlantic/Reykjavik", label: "Reykjavik", offset: "UTC+00:00" },
	{ value: "Africa/Sao_Tome", label: "Sao Tome", offset: "UTC+00:00" },
	{ value: "Atlantic/St_Helena", label: "St. Helena", offset: "UTC+00:00" },
	{ value: "UTC", label: "UTC", offset: "UTC+00:00" },
	{ value: "Africa/Algiers", label: "Algiers", offset: "UTC+01:00" },
	{ value: "Europe/Amsterdam", label: "Amsterdam", offset: "UTC+01:00" },
	{ value: "Europe/Andorra", label: "Andorra", offset: "UTC+01:00" },
	{ value: "Africa/Bangui", label: "Bangui", offset: "UTC+01:00" },
	{ value: "Europe/Belgrade", label: "Belgrade", offset: "UTC+01:00" },
	{ value: "Europe/Berlin", label: "Berlin", offset: "UTC+01:00" },
	{ value: "Europe/Bratislava", label: "Bratislava", offset: "UTC+01:00" },
	{ value: "Africa/Brazzaville", label: "Brazzaville", offset: "UTC+01:00" },
	{ value: "Europe/Brussels", label: "Brussels", offset: "UTC+01:00" },
	{ value: "Europe/Budapest", label: "Budapest", offset: "UTC+01:00" },
	{ value: "Europe/Busingen", label: "Busingen", offset: "UTC+01:00" },
	{ value: "Africa/Ceuta", label: "Ceuta", offset: "UTC+01:00" },
	{ value: "Europe/Copenhagen", label: "Copenhagen", offset: "UTC+01:00" },
	{ value: "Africa/Douala", label: "Douala", offset: "UTC+01:00" },
	{ value: "Europe/Gibraltar", label: "Gibraltar", offset: "UTC+01:00" },
	{ value: "Africa/Kinshasa", label: "Kinshasa", offset: "UTC+01:00" },
	{ value: "Africa/Lagos", label: "Lagos", offset: "UTC+01:00" },
	{ value: "Africa/Libreville", label: "Libreville", offset: "UTC+01:00" },
	{ value: "Europe/Ljubljana", label: "Ljubljana", offset: "UTC+01:00" },
	{ value: "Arctic/Longyearbyen", label: "Longyearbyen", offset: "UTC+01:00" },
	{ value: "Africa/Luanda", label: "Luanda", offset: "UTC+01:00" },
	{ value: "Europe/Luxembourg", label: "Luxembourg", offset: "UTC+01:00" },
	{ value: "Europe/Madrid", label: "Madrid", offset: "UTC+01:00" },
	{ value: "Africa/Malabo", label: "Malabo", offset: "UTC+01:00" },
	{ value: "Europe/Malta", label: "Malta", offset: "UTC+01:00" },
	{ value: "Europe/Monaco", label: "Monaco", offset: "UTC+01:00" },
	{ value: "Africa/Ndjamena", label: "Ndjamena", offset: "UTC+01:00" },
	{ value: "Africa/Niamey", label: "Niamey", offset: "UTC+01:00" },
	{ value: "Europe/Oslo", label: "Oslo", offset: "UTC+01:00" },
	{ value: "Europe/Paris", label: "Paris", offset: "UTC+01:00" },
	{ value: "Europe/Podgorica", label: "Podgorica", offset: "UTC+01:00" },
	{ value: "Africa/Porto-Novo", label: "Porto-Novo", offset: "UTC+01:00" },
	{ value: "Europe/Prague", label: "Prague", offset: "UTC+01:00" },
	{ value: "Europe/Rome", label: "Rome", offset: "UTC+01:00" },
	{ value: "Europe/San_Marino", label: "San Marino", offset: "UTC+01:00" },
	{ value: "Europe/Sarajevo", label: "Sarajevo", offset: "UTC+01:00" },
	{ value: "Europe/Skopje", label: "Skopje", offset: "UTC+01:00" },
	{ value: "Europe/Stockholm", label: "Stockholm", offset: "UTC+01:00" },
	{ value: "Europe/Tirane", label: "Tirane", offset: "UTC+01:00" },
	{ value: "Africa/Tripoli", label: "Tripoli", offset: "UTC+01:00" },
	{ value: "Africa/Tunis", label: "Tunis", offset: "UTC+01:00" },
	{ value: "Europe/Vaduz", label: "Vaduz", offset: "UTC+01:00" },
	{ value: "Europe/Vatican", label: "Vatican", offset: "UTC+01:00" },
	{ value: "Europe/Vienna", label: "Vienna", offset: "UTC+01:00" },
	{ value: "Europe/Warsaw", label: "Warsaw", offset: "UTC+01:00" },
	{ value: "Africa/Windhoek", label: "Windhoek", offset: "UTC+01:00" },
	{ value: "Europe/Zagreb", label: "Zagreb", offset: "UTC+01:00" },
	{ value: "Europe/Zurich", label: "Zurich", offset: "UTC+01:00" },
	{ value: "Europe/Athens", label: "Athens", offset: "UTC+02:00" },
	{ value: "Asia/Beirut", label: "Beirut", offset: "UTC+02:00" },
	{ value: "Africa/Blantyre", label: "Blantyre", offset: "UTC+02:00" },
	{ value: "Europe/Bucharest", label: "Bucharest", offset: "UTC+02:00" },
	{ value: "Africa/Bujumbura", label: "Bujumbura", offset: "UTC+02:00" },
	{ value: "Africa/Cairo", label: "Cairo", offset: "UTC+02:00" },
	{ value: "Europe/Chisinau", label: "Chisinau", offset: "UTC+02:00" },
	{ value: "Asia/Damascus", label: "Damascus", offset: "UTC+02:00" },
	{ value: "Africa/Gaborone", label: "Gaborone", offset: "UTC+02:00" },
	{ value: "Asia/Gaza", label: "Gaza", offset: "UTC+02:00" },
	{ value: "Africa/Harare", label: "Harare", offset: "UTC+02:00" },
	{ value: "Asia/Hebron", label: "Hebron", offset: "UTC+02:00" },
	{ value: "Europe/Helsinki", label: "Helsinki", offset: "UTC+02:00" },
	{ value: "Europe/Istanbul", label: "Istanbul", offset: "UTC+02:00" },
	{ value: "Asia/Jerusalem", label: "Jerusalem", offset: "UTC+02:00" },
	{ value: "Africa/Johannesburg", label: "Johannesburg", offset: "UTC+02:00" },
	{ value: "Europe/Kiev", label: "Kiev", offset: "UTC+02:00" },
	{ value: "Africa/Kigali", label: "Kigali", offset: "UTC+02:00" },
	{ value: "Africa/Lubumbashi", label: "Lubumbashi", offset: "UTC+02:00" },
	{ value: "Africa/Lusaka", label: "Lusaka", offset: "UTC+02:00" },
	{ value: "Africa/Maputo", label: "Maputo", offset: "UTC+02:00" },
	{ value: "Europe/Mariehamn", label: "Mariehamn", offset: "UTC+02:00" },
	{ value: "Africa/Maseru", label: "Maseru", offset: "UTC+02:00" },
	{ value: "Africa/Mbabane", label: "Mbabane", offset: "UTC+02:00" },
	{ value: "Asia/Nicosia", label: "Nicosia", offset: "UTC+02:00" },
	{ value: "Europe/Riga", label: "Riga", offset: "UTC+02:00" },
	{ value: "Europe/Simferopol", label: "Simferopol", offset: "UTC+02:00" },
	{ value: "Europe/Sofia", label: "Sofia", offset: "UTC+02:00" },
	{ value: "Europe/Tallinn", label: "Tallinn", offset: "UTC+02:00" },
	{ value: "Europe/Uzhgorod", label: "Uzhgorod", offset: "UTC+02:00" },
	{ value: "Europe/Vilnius", label: "Vilnius", offset: "UTC+02:00" },
	{ value: "Europe/Zaporozhye", label: "Zaporozhye", offset: "UTC+02:00" },
	{ value: "Africa/Addis_Ababa", label: "Addis Ababa", offset: "UTC+03:00" },
	{ value: "Asia/Aden", label: "Aden", offset: "UTC+03:00" },
	{ value: "Asia/Amman", label: "Amman", offset: "UTC+03:00" },
	{ value: "Indian/Antananarivo", label: "Antananarivo", offset: "UTC+03:00" },
	{ value: "Africa/Asmara", label: "Asmara", offset: "UTC+03:00" },
	{ value: "Asia/Baghdad", label: "Baghdad", offset: "UTC+03:00" },
	{ value: "Asia/Bahrain", label: "Bahrain", offset: "UTC+03:00" },
	{ value: "Indian/Comoro", label: "Comoro", offset: "UTC+03:00" },
	{
		value: "Africa/Dar_es_Salaam",
		label: "Dar es Salaam",
		offset: "UTC+03:00",
	},
	{ value: "Africa/Djibouti", label: "Djibouti", offset: "UTC+03:00" },
	{ value: "Africa/Juba", label: "Juba", offset: "UTC+03:00" },
	{ value: "Europe/Kaliningrad", label: "Kaliningrad", offset: "UTC+03:00" },
	{ value: "Africa/Kampala", label: "Kampala", offset: "UTC+03:00" },
	{ value: "Africa/Khartoum", label: "Khartoum", offset: "UTC+03:00" },
	{ value: "Asia/Kuwait", label: "Kuwait", offset: "UTC+03:00" },
	{ value: "Indian/Mayotte", label: "Mayotte", offset: "UTC+03:00" },
	{ value: "Europe/Minsk", label: "Minsk", offset: "UTC+03:00" },
	{ value: "Africa/Mogadishu", label: "Mogadishu", offset: "UTC+03:00" },
	{ value: "Europe/Moscow", label: "Moscow", offset: "UTC+03:00" },
	{ value: "Africa/Nairobi", label: "Nairobi", offset: "UTC+03:00" },
	{ value: "Asia/Qatar", label: "Qatar", offset: "UTC+03:00" },
	{ value: "Asia/Riyadh", label: "Riyadh", offset: "UTC+03:00" },
	{ value: "Antarctica/Syowa", label: "Syowa", offset: "UTC+03:00" },
	{ value: "Asia/Tehran", label: "Tehran", offset: "UTC+03:30" },
	{ value: "Asia/Baku", label: "Baku", offset: "UTC+04:00" },
	{ value: "Asia/Dubai", label: "Dubai", offset: "UTC+04:00" },
	{ value: "Indian/Mahe", label: "Mahe", offset: "UTC+04:00" },
	{ value: "Indian/Mauritius", label: "Mauritius", offset: "UTC+04:00" },
	{ value: "Asia/Muscat", label: "Muscat", offset: "UTC+04:00" },
	{ value: "Indian/Reunion", label: "Reunion", offset: "UTC+04:00" },
	{ value: "Europe/Samara", label: "Samara", offset: "UTC+04:00" },
	{ value: "Asia/Tbilisi", label: "Tbilisi", offset: "UTC+04:00" },
	{ value: "Europe/Volgograd", label: "Volgograd", offset: "UTC+04:00" },
	{ value: "Asia/Yerevan", label: "Yerevan", offset: "UTC+04:00" },
	{ value: "Asia/Kabul", label: "Kabul", offset: "UTC+04:30" },
	{ value: "Asia/Aqtau", label: "Aqtau", offset: "UTC+05:00" },
	{ value: "Asia/Aqtobe", label: "Aqtobe", offset: "UTC+05:00" },
	{ value: "Asia/Ashgabat", label: "Ashgabat", offset: "UTC+05:00" },
	{ value: "Asia/Dushanbe", label: "Dushanbe", offset: "UTC+05:00" },
	{ value: "Asia/Karachi", label: "Karachi", offset: "UTC+05:00" },
	{ value: "Indian/Kerguelen", label: "Kerguelen", offset: "UTC+05:00" },
	{ value: "Indian/Maldives", label: "Maldives", offset: "UTC+05:00" },
	{ value: "Antarctica/Mawson", label: "Mawson", offset: "UTC+05:00" },
	{ value: "Asia/Oral", label: "Oral", offset: "UTC+05:00" },
	{ value: "Asia/Samarkand", label: "Samarkand", offset: "UTC+05:00" },
	{ value: "Asia/Tashkent", label: "Tashkent", offset: "UTC+05:00" },
	{ value: "Asia/Colombo", label: "Colombo", offset: "UTC+05:30" },
	{ value: "Asia/Kolkata", label: "Kolkata", offset: "UTC+05:30" },
	{ value: "Asia/Kathmandu", label: "Kathmandu", offset: "UTC+05:45" },
	{ value: "Asia/Almaty", label: "Almaty", offset: "UTC+06:00" },
	{ value: "Asia/Bishkek", label: "Bishkek", offset: "UTC+06:00" },
	{ value: "Indian/Chagos", label: "Chagos", offset: "UTC+06:00" },
	{ value: "Asia/Dhaka", label: "Dhaka", offset: "UTC+06:00" },
	{ value: "Asia/Qyzylorda", label: "Qyzylorda", offset: "UTC+06:00" },
	{ value: "Asia/Thimphu", label: "Thimphu", offset: "UTC+06:00" },
	{ value: "Antarctica/Vostok", label: "Vostok", offset: "UTC+06:00" },
	{ value: "Asia/Yekaterinburg", label: "Yekaterinburg", offset: "UTC+06:00" },
	{ value: "Indian/Cocos", label: "Cocos", offset: "UTC+06:30" },
	{ value: "Asia/Rangoon", label: "Rangoon", offset: "UTC+06:30" },
	{ value: "Asia/Bangkok", label: "Bangkok", offset: "UTC+07:00" },
	{ value: "Indian/Christmas", label: "Christmas", offset: "UTC+07:00" },
	{ value: "Antarctica/Davis", label: "Davis", offset: "UTC+07:00" },
	{ value: "Asia/Ho_Chi_Minh", label: "Ho Chi Minh", offset: "UTC+07:00" },
	{ value: "Asia/Hovd", label: "Hovd", offset: "UTC+07:00" },
	{ value: "Asia/Jakarta", label: "Jakarta", offset: "UTC+07:00" },
	{ value: "Asia/Novokuznetsk", label: "Novokuznetsk", offset: "UTC+07:00" },
	{ value: "Asia/Novosibirsk", label: "Novosibirsk", offset: "UTC+07:00" },
	{ value: "Asia/Omsk", label: "Omsk", offset: "UTC+07:00" },
	{ value: "Asia/Phnom_Penh", label: "Phnom Penh", offset: "UTC+07:00" },
	{ value: "Asia/Pontianak", label: "Pontianak", offset: "UTC+07:00" },
	{ value: "Asia/Vientiane", label: "Vientiane", offset: "UTC+07:00" },
	{ value: "Asia/Brunei", label: "Brunei", offset: "UTC+08:00" },
	{ value: "Antarctica/Casey", label: "Casey", offset: "UTC+08:00" },
	{ value: "Asia/Choibalsan", label: "Choibalsan", offset: "UTC+08:00" },
	{ value: "Asia/Chongqing", label: "Chongqing", offset: "UTC+08:00" },
	{ value: "Asia/Harbin", label: "Harbin", offset: "UTC+08:00" },
	{ value: "Asia/Hong_Kong", label: "Hong Kong", offset: "UTC+08:00" },
	{ value: "Asia/Kashgar", label: "Kashgar", offset: "UTC+08:00" },
	{ value: "Asia/Krasnoyarsk", label: "Krasnoyarsk", offset: "UTC+08:00" },
	{ value: "Asia/Kuala_Lumpur", label: "Kuala Lumpur", offset: "UTC+08:00" },
	{ value: "Asia/Kuching", label: "Kuching", offset: "UTC+08:00" },
	{ value: "Asia/Macau", label: "Macau", offset: "UTC+08:00" },
	{ value: "Asia/Makassar", label: "Makassar", offset: "UTC+08:00" },
	{ value: "Asia/Manila", label: "Manila", offset: "UTC+08:00" },
	{ value: "Australia/Perth", label: "Perth", offset: "UTC+08:00" },
	{ value: "Asia/Shanghai", label: "Shanghai", offset: "UTC+08:00" },
	{ value: "Asia/Singapore", label: "Singapore", offset: "UTC+08:00" },
	{ value: "Asia/Taipei", label: "Taipei", offset: "UTC+08:00" },
	{ value: "Asia/Ulaanbaatar", label: "Ulaanbaatar", offset: "UTC+08:00" },
	{ value: "Asia/Urumqi", label: "Urumqi", offset: "UTC+08:00" },
	{ value: "Australia/Eucla", label: "Eucla", offset: "UTC+08:45" },
	{ value: "Asia/Dili", label: "Dili", offset: "UTC+09:00" },
	{ value: "Asia/Irkutsk", label: "Irkutsk", offset: "UTC+09:00" },
	{ value: "Asia/Jayapura", label: "Jayapura", offset: "UTC+09:00" },
	{ value: "Pacific/Palau", label: "Palau", offset: "UTC+09:00" },
	{ value: "Asia/Pyongyang", label: "Pyongyang", offset: "UTC+09:00" },
	{ value: "Asia/Seoul", label: "Seoul", offset: "UTC+09:00" },
	{ value: "Asia/Tokyo", label: "Tokyo", offset: "UTC+09:00" },
	{ value: "Australia/Adelaide", label: "Adelaide", offset: "UTC+09:30" },
	{ value: "Australia/Broken_Hill", label: "Broken Hill", offset: "UTC+09:30" },
	{ value: "Australia/Darwin", label: "Darwin", offset: "UTC+09:30" },
	{ value: "Australia/Brisbane", label: "Brisbane", offset: "UTC+10:00" },
	{ value: "Pacific/Chuuk", label: "Chuuk", offset: "UTC+10:00" },
	{ value: "Australia/Currie", label: "Currie", offset: "UTC+10:00" },
	{
		value: "Antarctica/DumontDUrville",
		label: "DumontDUrville",
		offset: "UTC+10:00",
	},
	{ value: "Pacific/Guam", label: "Guam", offset: "UTC+10:00" },
	{ value: "Australia/Hobart", label: "Hobart", offset: "UTC+10:00" },
	{ value: "Asia/Khandyga", label: "Khandyga", offset: "UTC+10:00" },
	{ value: "Australia/Lindeman", label: "Lindeman", offset: "UTC+10:00" },
	{ value: "Australia/Melbourne", label: "Melbourne", offset: "UTC+10:00" },
	{ value: "Pacific/Port_Moresby", label: "Port Moresby", offset: "UTC+10:00" },
	{ value: "Pacific/Saipan", label: "Saipan", offset: "UTC+10:00" },
	{ value: "Australia/Sydney", label: "Sydney", offset: "UTC+10:00" },
	{ value: "Asia/Yakutsk", label: "Yakutsk", offset: "UTC+10:00" },
	{ value: "Australia/Lord_Howe", label: "Lord Howe", offset: "UTC+10:30" },
	{ value: "Pacific/Efate", label: "Efate", offset: "UTC+11:00" },
	{ value: "Pacific/Guadalcanal", label: "Guadalcanal", offset: "UTC+11:00" },
	{ value: "Pacific/Kosrae", label: "Kosrae", offset: "UTC+11:00" },
	{ value: "Antarctica/Macquarie", label: "Macquarie", offset: "UTC+11:00" },
	{ value: "Pacific/Noumea", label: "Noumea", offset: "UTC+11:00" },
	{ value: "Pacific/Pohnpei", label: "Pohnpei", offset: "UTC+11:00" },
	{ value: "Asia/Sakhalin", label: "Sakhalin", offset: "UTC+11:00" },
	{ value: "Asia/Ust-Nera", label: "Ust-Nera", offset: "UTC+11:00" },
	{ value: "Asia/Vladivostok", label: "Vladivostok", offset: "UTC+11:00" },
	{ value: "Pacific/Norfolk", label: "Norfolk", offset: "UTC+11:30" },
	{ value: "Asia/Anadyr", label: "Anadyr", offset: "UTC+12:00" },
	{ value: "Pacific/Auckland", label: "Auckland", offset: "UTC+12:00" },
	{ value: "Pacific/Fiji", label: "Fiji", offset: "UTC+12:00" },
	{ value: "Pacific/Funafuti", label: "Funafuti", offset: "UTC+12:00" },
	{ value: "Asia/Kamchatka", label: "Kamchatka", offset: "UTC+12:00" },
	{ value: "Pacific/Kwajalein", label: "Kwajalein", offset: "UTC+12:00" },
	{ value: "Asia/Magadan", label: "Magadan", offset: "UTC+12:00" },
	{ value: "Pacific/Majuro", label: "Majuro", offset: "UTC+12:00" },
	{ value: "Antarctica/McMurdo", label: "McMurdo", offset: "UTC+12:00" },
	{ value: "Pacific/Nauru", label: "Nauru", offset: "UTC+12:00" },
	{ value: "Antarctica/South_Pole", label: "South Pole", offset: "UTC+12:00" },
	{ value: "Pacific/Tarawa", label: "Tarawa", offset: "UTC+12:00" },
	{ value: "Pacific/Wake", label: "Wake", offset: "UTC+12:00" },
	{ value: "Pacific/Wallis", label: "Wallis", offset: "UTC+12:00" },
	{ value: "Pacific/Chatham", label: "Chatham", offset: "UTC+12:45" },
	{ value: "Pacific/Apia", label: "Apia", offset: "UTC+13:00" },
	{ value: "Pacific/Enderbury", label: "Enderbury", offset: "UTC+13:00" },
	{ value: "Pacific/Fakaofo", label: "Fakaofo", offset: "UTC+13:00" },
	{ value: "Pacific/Tongatapu", label: "Tongatapu", offset: "UTC+13:00" },
	{ value: "Pacific/Kiritimati", label: "Kiritimati", offset: "UTC+14:00" },
];

export const getTimezoneByValue = (value: string): Timezone | undefined => {
	return timezones.find((tz) => tz.value === value);
};
