import { Application } from "../../types/applications";

// Define the table data using the interface
export const tableData: Application[] = [
	{
		id: 1,
		institution_details: {
			id: "123",
			rank: "5",
			name: "Harvard University",
			country: "United States",
			overall_score: "95.2",
		},
		institution: "Harvard University",
		institution_country: "USA",
		program_name: "Computer Science",
		degree_type: "Master",
		department: "School of Engineering",
		duration_years: 2,
		tuition_fee: 50000,
		application_link: "https://apply.harvard.edu",
		scholarship_link: "https://harvard.edu/scholarships",
		program_info_link: "https://harvard.edu/programs/cs",
		status: "Submitted",
		start_date: "2025-09-01",
		submitted_date: "2024-04-01",
		decision_date: "2024-06-15",
		notes:
			"Submitted all required documents. Waiting for interview invitation.",
		created_at: "2024-03-15T10:30:00Z",
		updated_at: "2024-04-01T15:45:00Z",
		user_id: 1234,
		program_id: 1001,
	},
	{
		id: 2,
		institution_details: {
			id: "234",
			rank: "12",
			name: "Stanford University",
			country: "United States",
			overall_score: "92.8",
		},
		institution: "Stanford University",
		institution_country: "USA",
		program_name: "Data Science",
		degree_type: "PhD",
		department: "School of Computing",
		duration_years: 4,
		tuition_fee: 60000,
		application_link: "https://apply.stanford.edu",
		scholarship_link: "https://stanford.edu/scholarships",
		program_info_link: "https://stanford.edu/programs/datascience",
		status: "Interview",
		start_date: "2025-08-15",
		submitted_date: "2024-02-15",
		decision_date: "2024-05-30",
		notes: "Interview scheduled for May 10th. Need to prepare presentation.",
		created_at: "2024-01-20T09:15:00Z",
		updated_at: "2024-04-25T11:30:00Z",
		user_id: 1234,
		program_id: 2002,
	},
	{
		id: 3,
		institution_details: {
			id: "345",
			rank: "8",
			name: "Massachusetts Institute of Technology",
			country: "United States",
			overall_score: "94.1",
		},
		institution: "MIT",
		institution_country: "USA",
		program_name: "Artificial Intelligence",
		degree_type: "Master",
		department: "Electrical Engineering & Computer Science",
		duration_years: 2.5,
		tuition_fee: 55000,
		application_link: "https://apply.mit.edu",
		scholarship_link: "https://mit.edu/scholarships",
		program_info_link: "https://mit.edu/programs/ai",
		status: "Accepted",
		start_date: "2025-09-01",
		submitted_date: "2024-01-10",
		decision_date: "2024-03-20",
		notes: "Accepted with partial scholarship! Need to respond by May 1st.",
		created_at: "2023-12-05T14:20:00Z",
		updated_at: "2024-03-20T16:45:00Z",
		user_id: 1234,
		program_id: 3003,
	},
	{
		id: 4,
		institution_details: {
			id: "456",
			rank: "22",
			name: "University of California, Berkeley",
			country: "United States",
			overall_score: "88.5",
		},
		institution: "UC Berkeley",
		institution_country: "USA",
		program_name: "Cybersecurity",
		degree_type: "Master",
		department: "College of Computing",
		duration_years: 1.5,
		tuition_fee: 45000,
		application_link: "https://apply.berkeley.edu",
		scholarship_link: "https://berkeley.edu/scholarships",
		program_info_link: "https://berkeley.edu/programs/cybersecurity",
		status: "Rejected",
		start_date: "2025-08-15",
		submitted_date: "2024-02-01",
		decision_date: "2024-04-15",
		notes:
			"Rejected - will apply again next cycle with stronger recommendations.",
		created_at: "2024-01-15T08:45:00Z",
		updated_at: "2024-04-15T13:10:00Z",
		user_id: 4321,
		program_id: 4004,
	},
	{
		id: 5,
		institution_details: {
			id: "567",
			rank: "18",
			name: "University of Oxford",
			country: "United Kingdom",
			overall_score: "91.3",
		},
		institution: "University of Oxford",
		institution_country: "UK",
		program_name: "Machine Learning",
		degree_type: "PhD",
		department: "Department of Computer Science",
		duration_years: 3.5,
		tuition_fee: 40000,
		application_link: "https://apply.oxford.ac.uk",
		scholarship_link: "https://oxford.ac.uk/scholarships",
		program_info_link: "https://oxford.ac.uk/programs/ml",
		status: "In Progress",
		start_date: "2025-10-01",
		submitted_date: "2024-03-01",
		decision_date: "2024-07-01",
		notes: "Need to complete statement of purpose. Deadline is June 15th.",
		created_at: "2024-03-30T11:20:00Z",
		updated_at: "2024-04-10T09:35:00Z",
		user_id: 4321,
		program_id: 5005,
	},
];
